# Time Series Analysis

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [42]:
stock_df = pd.read_csv('Stock analysis.csv')   # this parse_dates will convert the string into date objec of the pandas 
stock_df.head ()                                                  # making the date or time as the index of the dataframe is known as datetime index 
stock_df['Date']= pd.to_datetime(stock_df['Date'])
stock_df.set_index('Date',inplace=True)
print (type(stock_df.index))
print (stock_df.loc['2025-07'])    # stock values in the july month 

stock_df.sort_index(inplace=True)

print (stock_df.loc['2025-08-15':'2025-08-25'])  # stock values in the august month , if the indices are not in sorted form then it will give an erro 
                                                 # because the slicing only work on the sorted values not on the random 


# Resampling  :- changing the frequency from one form to another , like knowing about the weekly stock except of daily 
st_df = pd.read_csv ('Daily stock.csv')

st_df['Date']= pd.to_datetime(st_df['Date'])
st_df.set_index('Date',inplace=True)
st_df.sort_index(inplace=True)
st_df.head()
print (f"\n\nIt is the range from the 10 date 20 of month september")
print (st_df.loc['2024-09-10':'2024-09-20'])

st_df.Close.resample('M').mean()

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
              Open    High     Low   Close      Volume
Date
2025-07-31  208.49  209.84  207.16  207.57  80,698,430
2025-07-30  211.90  212.39  207.72  209.05  45,512,512
2025-07-29  214.18  214.81  210.82  211.27  51,411,719
              Open    High     Low   Close      Volume
Date
2025-08-15  234.00  234.28  229.34  231.59  56,038,660
2025-08-18  231.70  233.12  230.11  230.89  37,476,191
2025-08-19  231.28  232.87  229.35  230.56  39,402,559
2025-08-20  229.98  230.47  225.77  226.01  42,263,871
2025-08-21  226.27  226.52  223.78  224.90  30,621,250
2025-08-22  226.17  229.09  225.41  227.76  42,477,809
2025-08-25  226.48  229.30  226.23  227.16  30,983,131


It is the range from the 10 date 20 of month september
              Open    High     Low   Close       Volume
Date
2024-09-10  218.92  221.48  216.73  220.11   51,591,031
2024-09-11  221.46  223.09  217.89  222.66   44,587,070
2024-09-12  222.50  223.55  219.82  222.77   37,498,230
2024-09-13  223.58  224.04  221.91  222.50   36,766,621
2024-09-16  216.54  217.22  213.92  216.32   59,357,434
2024-09-17  215.75  216.90  214.50  216.79   45,519,340
2024-09-18  217.55  222.71  217.54  220.69   59,894,930
2024-09-19  224.99  229.82  224.63  228.87   66,781,320
2024-09-20  229.97  233.09  227.62  228.20  318,679,906

C:\Users\izaza\AppData\Local\Temp\ipykernel_1576\3228375508.py:24: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  st_df.Close.resample('M').mean()

Date
2024-08-31    229.395000
2024-09-30    223.758000
2024-10-31    230.056087
2024-11-30    227.810500
2024-12-31    249.322857
2025-01-31    234.587000
2025-02-28    238.513684
2025-03-31    222.702857
2025-04-30    201.183810
2025-05-31    203.947143
2025-06-30    200.657000
2025-07-31    211.280909
2025-08-31    224.647143
Freq: ME, Name: Close, dtype: float64

---

### Date Range

In [ ]:
jan_st = pd.read_csv ("January stock.csv")
# produce the dates using the range function 
date = pd.date_range(start='01-01-2025',end='28-01-2025' , freq='B')  # this will produce the dates 
jan_st.set_index (date, inplace=True)    # set that dates range as the index of the dataframe 


# generating some random series or dataframe 
rng = pd.date_range(start='1/1/2025', periods=50, freq='D')
rng 
dataf = pd.DataFrame(np.random.randint (1,20,len (rng)),index=rng)   # this is the way through which we can produce a random dataframe or the series 
dataf.head ()

             0
2025-01-01   8
2025-01-02   1
2025-01-03   9
2025-01-04  16
2025-01-05   9

### Timestamp , Period and Period index

In [34]:
year = pd.Period('2025')   # yearly 
year 

month = pd.Period('2025-12', freq='M')  # monthly 
month 

# with the help of this datetime object we can perform arthemtic operations 
year += 1 
print (year )
month += 1
print (month)
print (month.start_time)    
print (month.end_time)


period_range = pd.period_range(start='2025', periods=8 , freq='M')
print (period_range)

period_df = pd.DataFrame(np.random.randint(1 , 10 , len(period_range)))
period_df.set_index(period_range)
period_df
print (period_df.index )


# exercise 
walmart_df = pd.read_csv("walmart's stock data.csv")
walmart_df.set_index('Line Item',inplace =True)
walmart_df = walmart_df.T   # take transpose on the table  
# convert the index into period index 
walmart_df.index = pd.PeriodIndex(walmart_df.index , freq='Q-JAN')  # this will conver the index into perid index , 
walmart_df["Start_time"]=walmart_df.index.map(lambda x : x.start_time)
walmart_df['End_time']= walmart_df.index.map(lambda x : x.end_time)
walmart_df

2026
2026-01
2026-01-01 00:00:00
2026-01-31 23:59:59.999999999
PeriodIndex(['2025-01', '2025-02', '2025-03', '2025-04', '2025-05', '2025-06',
             '2025-07', '2025-08'],
            dtype='period[M]')
RangeIndex(start=0, stop=8, step=1)

Line Item  Revenue  Expenses  Profit Start_time                      End_time
2017Q1      115904     86544   29360 2016-02-01 2016-04-30 23:59:59.999999999
2017Q2      120854     89485   31369 2016-05-01 2016-07-31 23:59:59.999999999
2017Q3      118179     87484   30695 2016-08-01 2016-10-31 23:59:59.999999999
2017Q4      130936     97743   33193 2016-11-01 2017-01-31 23:59:59.999999999
2018Q1      117542     87688   29854 2017-02-01 2017-04-30 23:59:59.999999999

---

### Shifting and lagging

In [ ]:
microsoft_pd = pd.read_csv ('microsoft stock.csv')
microsoft_pd['Date Time']= pd.to_datetime(microsoft_pd['Date Time'])
microsoft_pd.set_index('Date Time', inplace=True)
microsoft_pd.shift(1)   # it's just shift the data to the right or to the left , depending on the parameters that you give to

                     Price
Date Time
2017-08-17 09:00:00  71.00
2017-08-17 09:15:00  71.67
2017-08-17 09:30:00  72.80
2017-08-17 10:00:00  73.00
2017-08-17 10:30:00  72.51
2017-08-17 11:00:00    NaN